name: Publish project to GitHub Packages
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-puslish.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
    permissions:
      contents: read
      packages: write
